id: IB30BBEF0
source: https://www.lotsawahouse.org
source_file: null
initial_creation_type: input
imported: '2022-05-30T18:23:13.419486'
last_modified: '2022-05-30T18:23:13.419517'
parser: null
source_metadata:
  title: Böpa Tulku Dongak Tenpe Nyima
  language: en
  description: 'Texts by and about Böpa Tulku Dongak Tenpe Nyima (bod pa sprul sku
    mdo sngags bstan pa''i nyi ma, 1898/1900/1902–1959):'
  volume:
    f59BE:
      title: Biography of Böpa Tulku Dongak Tenpé Nyima
      base_file: f59BE.txt
      order: 1
      parent: Biography
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
